// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Api.Data;

#nullable disable

namespace WebApp.Api.Migrations
{
    [DbContext(typeof(DiagLinkDbContext))]
    [Migration("20261002150215_AddConversationMessageVisuals")]
    partial class AddConversationMessageVisuals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApp.Api.Models.Entities.AiPricing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InputPricePerMillion")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("OutputPricePerMillion")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsageType")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "Model", "UsageType", "EffectiveFromUtc");

                    b.ToTable("AiPricing", "dbo");
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.AiUsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentVersion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("AssistantMessageId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("CallId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Deployment")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FoundryConversationId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("int");

                    b.Property<Guid?>("MachineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Model")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ModelSource")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("int");

                    b.Property<string>("ParentResponseId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResponseId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("int");

                    b.Property<string>("UsageType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("CompanyId", "CreatedAtUtc");

                    b.HasIndex("MachineId", "CreatedAtUtc");

                    b.HasIndex("UsageType", "CreatedAtUtc");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("AiUsageRecords", "chat");
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.BillingAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("AmountRemainingCents")
                        .HasColumnType("bigint");

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("bit");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CurrentPeriodEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CurrentPeriodStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LatestInvoiceId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LatestInvoiceStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SubscriptionStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.HasIndex("StripeCustomerId")
                        .IsUnique()
                        .HasFilter("[StripeCustomerId] IS NOT NULL");

                    b.HasIndex("StripeSubscriptionId")
                        .IsUnique()
                        .HasFilter("[StripeSubscriptionId] IS NOT NULL");

                    b.ToTable("BillingAccounts", "dbo");
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Companies", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.CompanyWallet", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("CompanyId");

                    b.ToTable("CompanyWallets", "dbo");
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Entreprise")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FoundryConversationId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Machine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MachineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TechnicalStateJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnicalSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserObjectId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("FoundryConversationId");

                    b.HasIndex("MachineId");

                    b.HasIndex("UserObjectId");

                    b.ToTable("Conversations", "chat");
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.ConversationMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSummarized")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TokenCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("ConversationMessages", "chat");
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.ConversationMessageVisual", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AssetKey")
                        .IsRequired()
                        .HasMaxLength(768)
                        .HasColumnType("nvarchar(768)");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<long>("ConversationMessageId")
                        .HasColumnType("bigint");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("Page")
                        .HasColumnType("int");

                    b.Property<string>("Tile")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationMessageId");

                    b.HasIndex("ConversationMessageId", "AssetKey")
                        .IsUnique();

                    b.ToTable("ConversationMessageVisuals", "chat", t =>
                        {
                            t.HasCheckConstraint("CK_ConversationMessageVisuals_AssetType", "[AssetType] IN ('full', 'tile')");

                            t.HasCheckConstraint("CK_ConversationMessageVisuals_DisplayOrder", "[DisplayOrder] >= 0");

                            t.HasCheckConstraint("CK_ConversationMessageVisuals_Page", "[Page] > 0");

                            t.HasCheckConstraint("CK_ConversationMessageVisuals_RequiredStrings", "LEN([DocumentId]) > 0 AND LEN([Name]) > 0 AND LEN([AssetKey]) > 0");
                        });
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.CreditLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AiUsageRecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BalanceAfter")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("BucketType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("CommercialCreditAmount")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExternalEventId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("MachineBillingPeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MachineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("RealAiCost")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("AiUsageRecordId");

                    b.HasIndex("ExternalEventId")
                        .IsUnique()
                        .HasFilter("[ExternalEventId] IS NOT NULL");

                    b.HasIndex("MachineBillingPeriodId");

                    b.HasIndex("CompanyId", "CreatedAtUtc");

                    b.HasIndex("MachineId", "CreatedAtUtc");

                    b.HasIndex(new[] { "AiUsageRecordId" }, "UX_CreditLedger_CompanyWalletUsage")
                        .IsUnique()
                        .HasFilter("[AiUsageRecordId] IS NOT NULL AND [BucketType] = 'CompanyWallet' AND [EntryType] = 'AiUsage'");

                    b.HasIndex(new[] { "AiUsageRecordId" }, "UX_CreditLedger_MachineIncludedUsage")
                        .IsUnique()
                        .HasFilter("[AiUsageRecordId] IS NOT NULL AND [BucketType] = 'MachineIncluded' AND [EntryType] = 'AiUsage'");

                    b.ToTable("CreditLedger", "dbo");

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.EmailOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastAttemptAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MachineRequestId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("NextAttemptAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("NotificationType")
                        .HasColumnType("int");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PaymentRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProviderOperationId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("RecipientName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentRequestId")
                        .HasFilter("[PaymentRequestId] IS NOT NULL");

                    b.HasIndex("MachineRequestId", "NotificationType")
                        .IsUnique();

                    b.HasIndex("Status", "NextAttemptAtUtc", "LockedUntilUtc");

                    b.ToTable("EmailOutbox", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_EmailOutbox_AttemptCount", "[AttemptCount] >= 0");

                            t.HasCheckConstraint("CK_EmailOutbox_Lease", "([LeaseId] IS NULL AND [LockedUntilUtc] IS NULL) OR ([LeaseId] IS NOT NULL AND [LockedUntilUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_EmailOutbox_NotificationType", "[NotificationType] >= 0 AND [NotificationType] <= 4");

                            t.HasCheckConstraint("CK_EmailOutbox_Sent", "([Status] = 0 AND [SentAtUtc] IS NULL) OR ([Status] = 1 AND [SentAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_EmailOutbox_Status", "[Status] >= 0 AND [Status] <= 1");
                        });
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.ExchangeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 10)
                        .HasColumnType("decimal(18,10)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BaseCurrency", "QuoteCurrency", "EffectiveFromUtc");

                    b.ToTable("ExchangeRates", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_ExchangeRates_Interval", "[EffectiveToUtc] IS NULL OR [EffectiveToUtc] > [EffectiveFromUtc]");

                            t.HasCheckConstraint("CK_ExchangeRates_Rate", "[Rate] > 0");
                        });
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.LoginCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("UserId");

                    b.ToTable("LoginCodes", "chat");
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AgentVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AgentVersion");

                    b.Property<string>("BlobPrefix")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("BlobPrefix");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("FoundryAgentId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("FoundryAgentId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProjectEndpoint")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ProjectEndpoint");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("VectorStoreId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("VectorStoreId");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyId", "Name");

                    b.ToTable("Machines", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.MachineBillingPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IncludedAiBudgetRealCost")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("IncludedAiUsedRealCost")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PeriodEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("MachineId", "PeriodStartUtc")
                        .IsUnique();

                    b.ToTable("MachineBillingPeriods", "dbo");
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.MachineRequestPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActivatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("AmountCents")
                        .HasColumnType("bigint");

                    b.Property<string>("AuthorizationEventId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("AuthorizedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CapturedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<int>("EstimatedTotalPages")
                        .HasColumnType("int");

                    b.Property<long?>("FinalCaptureAmountCents")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FirstPeriodEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("MachineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MachineRequestId")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("PreparationStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("ProvisioningCompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProvisioningStage")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadyAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReadyByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RequestKind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("RequestLinkedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RequestedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("ServiceAmountCents")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StripeSessionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("TargetMachineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationEventId")
                        .IsUnique()
                        .HasFilter("[AuthorizationEventId] IS NOT NULL");

                    b.HasIndex("CompanyId")
                        .HasFilter("[CompanyId] IS NOT NULL");

                    b.HasIndex("MachineId")
                        .IsUnique()
                        .HasFilter("[MachineId] IS NOT NULL");

                    b.HasIndex("MachineRequestId")
                        .IsUnique()
                        .HasFilter("[MachineRequestId] IS NOT NULL");

                    b.HasIndex("StripePaymentIntentId")
                        .IsUnique()
                        .HasFilter("[StripePaymentIntentId] IS NOT NULL");

                    b.HasIndex("StripeSessionId")
                        .IsUnique()
                        .HasFilter("[StripeSessionId] IS NOT NULL");

                    b.HasIndex("TargetMachineId")
                        .HasFilter("[TargetMachineId] IS NOT NULL");

                    b.ToTable("MachineRequestPayments", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_MachineRequestPayments_Amount", "[AmountCents] > 0");

                            t.HasCheckConstraint("CK_MachineRequestPayments_Currency", "[Currency] = 'EUR'");

                            t.HasCheckConstraint("CK_MachineRequestPayments_FinalCaptureAmount", "[FinalCaptureAmountCents] IS NULL OR ([FinalCaptureAmountCents] > 0 AND [FinalCaptureAmountCents] <= [AmountCents])");

                            t.HasCheckConstraint("CK_MachineRequestPayments_FirstPeriod", "([ActivatedAtUtc] IS NULL AND [FirstPeriodEndUtc] IS NULL) OR ([ActivatedAtUtc] IS NOT NULL AND [FirstPeriodEndUtc] IS NOT NULL AND [ActivatedAtUtc] < [FirstPeriodEndUtc])");

                            t.HasCheckConstraint("CK_MachineRequestPayments_Link", "([MachineRequestId] IS NULL AND [RequestLinkedAtUtc] IS NULL) OR ([MachineRequestId] IS NOT NULL AND [RequestLinkedAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_MachineRequestPayments_Pages", "[EstimatedTotalPages] > 0");

                            t.HasCheckConstraint("CK_MachineRequestPayments_PreparationStatus", "[PreparationStatus] >= 0 AND [PreparationStatus] <= 1");

                            t.HasCheckConstraint("CK_MachineRequestPayments_ProvisioningCompleted", "([ProvisioningStage] < 6 AND [ProvisioningCompletedAtUtc] IS NULL) OR ([ProvisioningStage] = 6 AND [ProvisioningCompletedAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_MachineRequestPayments_ProvisioningStage", "[ProvisioningStage] >= 0 AND [ProvisioningStage] <= 6");

                            t.HasCheckConstraint("CK_MachineRequestPayments_Ready", "([PreparationStatus] = 0 AND [ReadyAtUtc] IS NULL AND [ReadyByUserId] IS NULL) OR ([PreparationStatus] = 1 AND [ReadyAtUtc] IS NOT NULL AND [ReadyByUserId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_MachineRequestPayments_RequestKind", "[RequestKind] >= 0 AND [RequestKind] <= 2");

                            t.HasCheckConstraint("CK_MachineRequestPayments_ServiceAmount", "[ServiceAmountCents] IS NULL OR ([ServiceAmountCents] >= 0 AND [ServiceAmountCents] <= 1990)");

                            t.HasCheckConstraint("CK_MachineRequestPayments_State", "([Status] = 0 AND [StripePaymentIntentId] IS NULL AND [AuthorizationEventId] IS NULL AND [AuthorizedAtUtc] IS NULL AND [CapturedAtUtc] IS NULL AND [CancelledAtUtc] IS NULL) OR ([Status] = 1 AND [StripePaymentIntentId] IS NOT NULL AND [AuthorizationEventId] IS NOT NULL AND [AuthorizedAtUtc] IS NOT NULL AND [CapturedAtUtc] IS NULL AND [CancelledAtUtc] IS NULL) OR ([Status] = 2 AND [StripePaymentIntentId] IS NOT NULL AND [AuthorizationEventId] IS NOT NULL AND [AuthorizedAtUtc] IS NOT NULL AND [CapturedAtUtc] IS NOT NULL AND [CancelledAtUtc] IS NULL) OR ([Status] = 3 AND [StripePaymentIntentId] IS NOT NULL AND [AuthorizationEventId] IS NOT NULL AND [AuthorizedAtUtc] IS NOT NULL AND [CapturedAtUtc] IS NULL AND [CancelledAtUtc] IS NOT NULL) OR ([Status] = 4 AND [StripePaymentIntentId] IS NULL AND [AuthorizationEventId] IS NULL AND [AuthorizedAtUtc] IS NULL AND [CapturedAtUtc] IS NULL AND [CancelledAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_MachineRequestPayments_Status", "[Status] >= 0 AND [Status] <= 4");

                            t.HasCheckConstraint("CK_MachineRequestPayments_Timestamps", "[UpdatedAtUtc] >= [CreatedAtUtc]");
                        });
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.StripeLifecycleEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("MachineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("StripeLifecycleEvents", "dbo");
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.StripeMachineAddition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActivatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("AiAmountCents")
                        .HasColumnType("int");

                    b.Property<Guid>("BillingAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CycleEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CycleStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalEventId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("MachineBillingPeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("OriginalQuantity")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PaymentConfirmedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentReference")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ServiceAmountCents")
                        .HasColumnType("int");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StripeInvoiceId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StripePriceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StripeSubscriptionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StripeSubscriptionItemId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("TargetQuantity")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BillingAccountId");

                    b.HasIndex("CompanyId")
                        .IsUnique()
                        .HasFilter("[CompletedAtUtc] IS NULL");

                    b.HasIndex("ExternalEventId")
                        .IsUnique()
                        .HasFilter("[ExternalEventId] IS NOT NULL");

                    b.HasIndex("MachineBillingPeriodId");

                    b.HasIndex("StripeInvoiceId")
                        .IsUnique()
                        .HasFilter("[StripeInvoiceId] IS NOT NULL");

                    b.HasIndex("MachineId", "CycleStartUtc")
                        .IsUnique();

                    b.ToTable("StripeMachineAdditions", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_StripeMachineAdditions_Amounts", "[AiAmountCents] = 1000 AND [ServiceAmountCents] >= 0 AND [ServiceAmountCents] <= 1990");

                            t.HasCheckConstraint("CK_StripeMachineAdditions_Completed", "([Stage] < 6 AND [CompletedAtUtc] IS NULL) OR ([Stage] = 6 AND [CompletedAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_StripeMachineAdditions_Cycle", "[CycleStartUtc] <= [ActivatedAtUtc] AND [ActivatedAtUtc] < [CycleEndUtc]");

                            t.HasCheckConstraint("CK_StripeMachineAdditions_Invoice", "[Stage] < 2 OR [StripeInvoiceId] IS NOT NULL");

                            t.HasCheckConstraint("CK_StripeMachineAdditions_Payment", "([Stage] < 4 AND [PaymentReference] IS NULL AND [PaymentConfirmedAtUtc] IS NULL) OR ([Stage] >= 4 AND [PaymentReference] IS NOT NULL AND [PaymentReference] <> '' AND [PaymentConfirmedAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_StripeMachineAdditions_Period", "([Stage] < 5 AND [MachineBillingPeriodId] IS NULL) OR ([Stage] >= 5 AND [MachineBillingPeriodId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_StripeMachineAdditions_Quantity", "[OriginalQuantity] >= 0 AND [TargetQuantity] = [OriginalQuantity] + 1");

                            t.HasCheckConstraint("CK_StripeMachineAdditions_Stage", "[Stage] >= 0 AND [Stage] <= 6");
                        });
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.StripeSubscriptionPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AmountPaidCents")
                        .HasColumnType("bigint");

                    b.Property<string>("BillingReason")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalEventId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MachineIdsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentConfirmedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentReference")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("PeriodEndUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PeriodStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("StripeInvoiceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StripeSubscriptionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ExternalEventId")
                        .IsUnique();

                    b.HasIndex("StripeInvoiceId")
                        .IsUnique();

                    b.HasIndex("StripeSubscriptionId", "PeriodStartUtc")
                        .IsUnique();

                    b.ToTable("StripeSubscriptionPayments", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_StripeSubscriptionPayments_Amount", "[AmountPaidCents] > 0");

                            t.HasCheckConstraint("CK_StripeSubscriptionPayments_Cycle", "[PeriodEndUtc] > [PeriodStartUtc]");

                            t.HasCheckConstraint("CK_StripeSubscriptionPayments_Reason", "[BillingReason] IN ('subscription_create', 'subscription_cycle')");
                        });
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.StripeWalletTopUp", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AmountCents")
                        .HasColumnType("int");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("ExternalEventId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("LedgerEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaymentConfirmedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ReturnUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StripePaymentIntentId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("StripeSessionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalEventId")
                        .IsUnique()
                        .HasFilter("[ExternalEventId] IS NOT NULL");

                    b.HasIndex("LedgerEntryId")
                        .IsUnique()
                        .HasFilter("[LedgerEntryId] IS NOT NULL");

                    b.HasIndex("StripePaymentIntentId")
                        .IsUnique()
                        .HasFilter("[StripePaymentIntentId] IS NOT NULL");

                    b.HasIndex("StripeSessionId")
                        .IsUnique()
                        .HasFilter("[StripeSessionId] IS NOT NULL");

                    b.HasIndex("CompanyId", "CreatedAtUtc");

                    b.ToTable("StripeWalletTopUps", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_StripeWalletTopUps_Amount", "[AmountCents] >= 1000 AND [AmountCents] <= 99999999 AND [Currency] = 'EUR'");

                            t.HasCheckConstraint("CK_StripeWalletTopUps_Completed", "([Stage] < 5 AND [CompletedAtUtc] IS NULL) OR ([Stage] = 5 AND [CompletedAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_StripeWalletTopUps_Ledger", "([Stage] < 4 AND [LedgerEntryId] IS NULL) OR ([Stage] >= 4 AND [LedgerEntryId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_StripeWalletTopUps_Payment", "([Stage] < 3 AND [StripePaymentIntentId] IS NULL AND [PaymentConfirmedAtUtc] IS NULL) OR ([Stage] >= 3 AND [StripePaymentIntentId] IS NOT NULL AND [PaymentConfirmedAtUtc] IS NOT NULL AND [ExternalEventId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_StripeWalletTopUps_Session", "[Stage] = 0 OR [StripeSessionId] IS NOT NULL");

                            t.HasCheckConstraint("CK_StripeWalletTopUps_Stage", "[Stage] >= 0 AND [Stage] <= 5");
                        });
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("EntraObjectId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.UserMachineAccess", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.HasKey("UserId", "MachineId");

                    b.HasIndex("MachineId");

                    b.HasIndex("UserId");

                    b.ToTable("UserMachines", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("UserSessions", "chat");
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.BillingAccount", b =>
                {
                    b.HasOne("WebApp.Api.Models.Entities.Company", null)
                        .WithOne()
                        .HasForeignKey("WebApp.Api.Models.Entities.BillingAccount", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.CompanyWallet", b =>
                {
                    b.HasOne("WebApp.Api.Models.Entities.Company", null)
                        .WithOne()
                        .HasForeignKey("WebApp.Api.Models.Entities.CompanyWallet", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.Conversation", b =>
                {
                    b.HasOne("WebApp.Api.Models.Entities.Machine", null)
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.ConversationMessage", b =>
                {
                    b.HasOne("WebApp.Api.Models.Entities.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.ConversationMessageVisual", b =>
                {
                    b.HasOne("WebApp.Api.Models.Entities.ConversationMessage", "ConversationMessage")
                        .WithMany("Visuals")
                        .HasForeignKey("ConversationMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConversationMessage");
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.CreditLedgerEntry", b =>
                {
                    b.HasOne("WebApp.Api.Models.Entities.AiUsageRecord", null)
                        .WithMany()
                        .HasForeignKey("AiUsageRecordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApp.Api.Models.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApp.Api.Models.Entities.MachineBillingPeriod", null)
                        .WithMany()
                        .HasForeignKey("MachineBillingPeriodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApp.Api.Models.Entities.Machine", null)
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.Machine", b =>
                {
                    b.HasOne("WebApp.Api.Models.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.MachineBillingPeriod", b =>
                {
                    b.HasOne("WebApp.Api.Models.Entities.Machine", null)
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.MachineRequestPayment", b =>
                {
                    b.HasOne("WebApp.Api.Models.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApp.Api.Models.Entities.Machine", null)
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApp.Api.Models.Entities.Machine", null)
                        .WithMany()
                        .HasForeignKey("TargetMachineId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.StripeLifecycleEvent", b =>
                {
                    b.HasOne("WebApp.Api.Models.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.StripeMachineAddition", b =>
                {
                    b.HasOne("WebApp.Api.Models.Entities.BillingAccount", null)
                        .WithMany()
                        .HasForeignKey("BillingAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApp.Api.Models.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApp.Api.Models.Entities.MachineBillingPeriod", null)
                        .WithMany()
                        .HasForeignKey("MachineBillingPeriodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApp.Api.Models.Entities.Machine", null)
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.StripeSubscriptionPayment", b =>
                {
                    b.HasOne("WebApp.Api.Models.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.StripeWalletTopUp", b =>
                {
                    b.HasOne("WebApp.Api.Models.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApp.Api.Models.Entities.CreditLedgerEntry", null)
                        .WithMany()
                        .HasForeignKey("LedgerEntryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.UserMachineAccess", b =>
                {
                    b.HasOne("WebApp.Api.Models.Entities.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("WebApp.Api.Models.Entities.ConversationMessage", b =>
                {
                    b.Navigation("Visuals");
                });
#pragma warning restore 612, 618
        }
    }
}
